name: Optimize Images

on:
  push:
    paths:
      - 'assets/imgs/**'
      - 'assets/portfolio/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install WebP tools
        run: sudo apt-get install -y webp

      - name: Convert images to WebP
        run: |
          find ./assets/imgs ./assets/portfolio -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) | while read img; do
            cwebp -q 90 "$img" -o "${img%.*}.webp"
          done

      - name: Commit optimized images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: optimize images"
