name: Optimize Images

on:
  push:
    paths:
      - 'assets/imgs/**'   # runs only when imgs change
      - 'assets/portfolio/**' # runs only when imgs change
  workflow_dispatch:       # allows you to run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Convert images to WebP
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: false  # keep original + add .webp
          quality: 90          # high quality for designers

      - name: Commit optimized images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: optimize images"
